name: "Dataiku GitOps Action"
description: "Run Dataiku GitOps workflow"
inputs:
  python-script:
    description: "Path to the Python script to run"
    required: true
  dataiku_api_token:
    description: "Dataiku API token"
    required: true
  dataiku_instance_a_url:
    description: "URL of the development Dataiku instance"
    required: true
  dataiku_instance_b_url:
    description: "URL of the staging Dataiku instance"
    required: true
  dataiku_project_key:
    description: "Key of the Dataiku project"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
      shell: bash

    - name: Install Dataiku Python API
      run: |
        curl -k -o dataiku.zip ${{ inputs.dataiku_instance_a_url }}/public/api/packages/dataiku.zip
        unzip dataiku.zip -d dataiku
        python -m pip install ./dataiku
      shell: bash

    - name: Run Dataiku GitOps Action
      env:
        DATAIKU_API_TOKEN: ${{ inputs.dataiku_api_token }}
        DATAIKU_INSTANCE_A_URL: ${{ inputs.dataiku_instance_a_url }}
        DATAIKU_INSTANCE_B_URL: ${{ inputs.dataiku_instance_b_url }}
        DATAIKU_PROJECT_KEY: ${{ inputs.dataiku_project_key }}
      run: |
        python ${{ github.action_path }}/dataiku_gitops_action.py
      shell: bash
