name: "Dataiku GitOps Action"
description: "Run Dataiku GitOps workflow"
inputs:
  python-script:
    description: "Path to the Python script to run"
    required: true
  dataiku_api_token_dev:
    description: "Dataiku API token for the DEV instance"
    required: true
  dataiku_api_token_staging:
    description: "Dataiku API token for the Staging instance"
    required: true
  dataiku_api_token_prod:
    description: "Dataiku API token for the Prod instance"
    required: true
  dataiku_instance_dev_url:
    description: "URL of the DEV Dataiku instance"
    required: true
  dataiku_instance_staging_url:
    description: "URL of the Staging Dataiku instance"
    required: true
  dataiku_instance_prod_url:
    description: "URL of the Prod Dataiku instance"
    required: true
  dataiku_project_key:
    description: "Key of the Dataiku project"
    required: true
  dataiku_infra_id_staging:
    description: "Infra ID for the Staging instance"
    required: true
  dataiku_infra_id_prod:
    description: "Infra ID for the Prod instance"
    required: true
  run_tests_only:
    description: "Run tests only on staging"
    required: false
    default: "true"
  client_certificate:
    description: "Client certificate for the Dataiku instances"
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas dataiku-api-client pytest
      shell: bash

    - name: Run Dataiku GitOps Action
      env:
        DATAIKU_API_TOKEN_DEV: ${{ inputs.dataiku_api_token_dev }}
        DATAIKU_API_TOKEN_STAGING: ${{ inputs.dataiku_api_token_staging }}
        DATAIKU_API_TOKEN_PROD: ${{ inputs.dataiku_api_token_prod }}
        DATAIKU_INSTANCE_DEV_URL: ${{ inputs.dataiku_instance_dev_url }}
        DATAIKU_INSTANCE_STAGING_URL: ${{ inputs.dataiku_instance_staging_url }}
        DATAIKU_INSTANCE_PROD_URL: ${{ inputs.dataiku_instance_prod_url }}
        DATAIKU_PROJECT_KEY: ${{ inputs.dataiku_project_key }}
        DATAIKU_INFRA_ID_STAGING: ${{ inputs.dataiku_infra_id_staging }}
        DATAIKU_INFRA_ID_PROD: ${{ inputs.dataiku_infra_id_prod }}
        RUN_TESTS_ONLY: ${{ inputs.run_tests_only }}
        PYTHON_SCRIPT: ${{ inputs.python-script }}
        CLIENT_CERTIFICATE: ${{ inputs.client_certificate }}
      run: |
        python ${{ github.action_path }}/dataiku_gitops_action.py
      shell: bash
